### ISSUE TITLE
Top row of Tabs overlap with gui, looks ugly with traslucent gui resource packs

### ISSUE THREAD

**Issue by CodeF53** [cakewhip/inventorytabs#20]
![image](https://user-images.githubusercontent.com/37855219/176235592-fcb60687-d363-4e7c-8a09-49177f8a7e6b.png)

I guess this was comes from a stylistic choice to have the active tab a bit higher than the other tabs.
Perhaps you could add an option to disable this?

**Comment by ghost** [comment]
AFAIK this repo has been unmaintained for over a year, I would use one of the forks that are more up to date.

**Comment by CodeF53** [comment]
I accidentally put this issue on tyne wrong fork, thanks for letting me know
