### ISSUE TITLE
Incompatible mod set

### ISSUE THREAD

**Issue by pikachub2005** [cakewhip/inventorytabs#21]
Error:
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Inventory Tabs' (inventorytabs) 0.8.1-1.19.x with any version that is compatible with:
		 - minecraft 1.18.2
Unmet dependency listing:
	 - Mod 'Inventory Tabs' (inventorytabs) 0.8.1-1.19.x requires any 1.19.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	 - Mod 'Inventory Tabs' (inventorytabs) 0.8.1-1.19.x requires any version of cloth-config2, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by ghost** [comment]
This repo is unmaintained, but it looks like your problem is that your version of the mod does not match the minecraft version.

**Comment by pikachub2005** [comment]
> This repo is unmaintained, but it looks like your problem is that your version of the mod does not match the minecraft version.

I'm using the fabric for 1.18.2 and this is the [updated mod](https://www.curseforge.com/minecraft/mc-mods/inventory-tabs-updated), so idk

**Comment by ghost** [comment]
you seem to have picked the 1.19 version of the mod, but this is not the correct repo for the updated version

**Comment by pikachub2005** [comment]
> you seem to have picked the 1.19 version of the mod, but this is not the correct repo for the updated version

Hmm you're right. I'm sure I picked the right one though... thanks =P
